### PR TITLE
What's up with those indetations? Fixed em.

### PR DESCRIPTION
**Pull request by Sascha8a**
Removed unnecessary functions and fixed indentations. Whatever was up with those.

### CODE REVIEW

**Comment by MissyMelissa** [comment]
Um you didn't really fix anything here either (like in #11), you just made it even more conflicting.

**Comment by MissyMelissa** [comment]
The rest of the code is 4 spaces, not tabs, so stick with that.

**Comment by Sascha8a** [comment]
Done.

**Comment by MissyMelissa** [comment]
Thx!

**Pull request merged**
