### PR TITLE
Minifications for everyone!

### PR DESCRIPTION
**Pull request by Sascha8a**

### CODE REVIEW

**Comment by MissyMelissa** [comment]
Why do the contents of this script differ from [this one](https://d3js.org/d3.v2.min.js)?

**Comment by Sascha8a** [comment]
I'm not sure about that, I took the old files and ran em through this tool: https://jscompress.com/

**Comment by MissyMelissa** [comment]
I suggest using the official one instead (and making sure it actually works in-game!)

**Comment by Sascha8a** [comment]
Now uses the official one. Results of in-game tests will be postet soon.

**Pull request closed without merging**
